# Generated by Django 5.0.4 on 2024-04-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patient_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='client',
            new_name='patient',
        ),
    ]
