# Generated by Django 5.0.4 on 2024-04-20 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_doctors_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='added_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='second_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
