# Generated by Django 5.0.4 on 2024-04-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_added_date_doctor_email_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='added_date',
            field=models.DateField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
